In [60]:
import numpy as np

class Node:
    def __init__(self, value, weight = 1):
        self.val = value
        self.weight = weight
        self.next = None


adjacency matrix

In [61]:
def max_edges(arr):
    max = 0
    head = None
    tail = None

    for i in range(len(arr)):
        temp = row_max(arr[i])

        if temp > max:
            head = Node(i)
            tail = head
            max = temp

        elif temp == max:
            tail.next = Node(i)
            tail = tail.next
    
    return head, max

def row_max(arr, count = 0, sum = 0):
    if count == len(arr):
        return sum
    
    return arr[count] + row_max(arr, count + 1, sum)

def tuple_to_matrix(items, num):
    new = np.zeros((num,num), int)
    for i in items:
        new[i[0]][i[1]] = 1
        new[i[1]][i[0]] = 1
    return new

def tuple_to_weight_matrix(items, num):
    new = np.zeros((num,num), int)
    for i in items:
        new[i[0]][i[1]] = i[2]
        new[i[1]][i[0]] = i[2]
    return new

def tuple_to_direct_matrix(items, num):
    new = np.zeros((num,num), int)
    for i in items:
        new[i[0]][i[1]] = 1
    return new

def tuple_to_direct_weight_matrix(items, num):
    new = np.zeros((num,num), int)
    for i in items:
        new[i[0]][i[1]] = i[2]
    return new

In [62]:
# task 01
def max_degre(items, num):
    arr = tuple_to_matrix(items, num)
    temp = max_edges(arr)
    head = temp[0]
    print("Vertex with max degree: ",end='')
    while head:
        print (head.val,end=' ')
        head = head.next
    print()
    print("max degree ",temp[1])

graph = ((3, 6),(6, 7),(6, 8),(6, 9),(9, 10),(0, 3),(2, 5),(0, 4),(0, 5),(1, 4),(1, 5),(2, 3),(2, 4),(4, 5),(7, 8),(8, 9),(7, 9))

curr = max_degre(graph, 11)


Vertex with max degree: 4 5 6 9 
max degree  4


In [63]:
# task 02
def max_weight(items, num):
    arr = tuple_to_weight_matrix(items, num)
    temp = max_edges(arr)
    head = temp[0]
    print("Vertex with max edge weight: ",end='')
    while head:
        print (head.val,end=' ')
        head = head.next
    print()
    print("max edge weight ",temp[1])

graph = ((3, 6, 10),(6, 7, 5),(6, 8, 5),(6, 9, 5),(9, 10, 40),(0, 3, 10),(2, 5, 20),(0, 4, 5),(0, 5, 15),(1, 4, 15),(1, 5, 10),(2, 3, 10),(2, 4, 15),(4, 5, 25),(7, 8, 10),(8, 9, 5),(7, 9,20))
max_weight(graph, 11)

Vertex with max edge weight: 5 9 
max edge weight  70


In [64]:
# task 03
# sub task 01
def max_out_degree(items, num):
    arr = tuple_to_direct_matrix(items, num)
    temp = max_edges(arr)
    head = temp[0]
    print("Vertex with max out degree: ",end='')
    while head:
        print (head.val,end=' ')
        head = head.next
    print()
    print("max out degree ",temp[1])

# sub task 02
def max_out_weight(items, num):
    arr = tuple_to_direct_weight_matrix(items,num)
    temp = max_edges(arr)
    head = temp[0]
    print("Vertex with max out weight: ",end='')
    while head:
        print (head.val,end=' ')
        head = head.next
    print()
    print("max out weight ",temp[1])

graph = ((3, 6),(6, 7),(6, 8),(6, 9),(9, 10),(0, 3),(2, 5),(0, 4),(0, 5),(1, 4),(1, 5),(2, 3),(2, 4),(4, 5),(7, 8),(8, 9),(7, 9))

max_out_degree(graph, 11)
print()         

graph = ((3, 6, 10),(6, 7, 5),(6, 8, 5),(6, 9, 5),(9, 10, 40),(0, 3, 10),(2, 5, 20),(0, 4, 5),(0, 5, 15),(1, 4, 15),(1, 5, 10),(2, 3, 10),(2, 4, 15),(4, 5, 25),(7, 8, 10),(8, 9, 5),(7, 9,20))
max_out_weight(graph, 11)

Vertex with max out degree: 0 2 6 
max out degree  3

Vertex with max out weight: 2 
max out weight  45


In [65]:
# task 04
def direct_to_undirect(items, num):
    arr = tuple_to_direct_weight_matrix(items, num)
    new = np.zeros((len(arr),len(arr)), int)
    for row in range(len(arr)):
        for col in range(len(arr)):
            if new[col][row] == 0:
                new[row][col] = arr[row][col]
                new[col][row] = arr[row][col]
    return new


graph = ((3, 6, 10),(6, 7, 5),(6, 8, 5),(6, 9, 5),(9, 10, 40),(0, 3, 10),(2, 5, 20),(0, 4, 5),(0, 5, 15),(1, 4, 15),(1, 5, 10),(2, 3, 10),(2, 4, 15),(4, 5, 25),(7, 8, 10),(8, 9, 5),(7, 9,20))
print(direct_to_undirect(graph, 11))

[[ 0  0  0 10  5 15  0  0  0  0  0]
 [ 0  0  0  0 15 10  0  0  0  0  0]
 [ 0  0  0 10 15 20  0  0  0  0  0]
 [10  0 10  0  0  0 10  0  0  0  0]
 [ 5 15 15  0  0 25  0  0  0  0  0]
 [15 10 20  0 25  0  0  0  0  0  0]
 [ 0  0  0 10  0  0  0  5  5  5  0]
 [ 0  0  0  0  0  0  5  0 10 20  0]
 [ 0  0  0  0  0  0  5 10  0  5  0]
 [ 0  0  0  0  0  0  5 20  5  0 40]
 [ 0  0  0  0  0  0  0  0  0 40  0]]


adjacency list

In [66]:
def max_edges_2(arr):
    head = None
    tail = None
    max = 0
    for i in range(len(arr)):
        if arr[i] != 0:
            temp = edge_sum(arr[i])
            if temp > max:
                head = Node(i)
                tail = head
                max = temp

            elif temp == max:
                tail.next = Node(i)
                tail = tail.next 

    return head, max
    

def edge_sum(head):
    if not head:
        return 0
    return head.weight + edge_sum(head.next)

def tuple_to_array(items, num):
    new = np.zeros(num,dtype=object)
    for i in items:

        if new[i[0]] == 0:
            new[i[0]] = Node(i[1])
        else:
            current = Node(i[1])
            current.next = new[i[0]]
            new[i[0]] = current

        if new[i[1]] == 0:
            new[i[1]] = Node(i[0])
        else:
            current = Node(i[0])
            current.next = new[i[1]]
            new[i[1]] = current

    return new 

def tuple_to_weight_array(items, num):
    new = np.zeros(num,dtype=object)
    for i in items:
        

        if new[i[0]] == 0:
            new[i[0]] = Node(i[1], i[2])
        else:
            current = Node(i[1], i[2]) 
            current.next = new[i[0]]
            new[i[0]] = current

        if new[i[1]] == 0:
            new[i[1]] = Node(i[0], i[2])
        else:
            current = Node(i[0], i[2])
            current.next = new[i[1]]
            new[i[1]] = current

    return new

def tuple_to_direct_array(items, num):
    new = np.zeros(num,dtype=object)
    for i in items:
        if new[i[0]] == 0:
            new[i[0]] = Node(i[1])
        else:
            current = Node(i[1])
            current.next = new[i[0]]
            new[i[0]] = current
    return new

def tuple_to_direct_weight_array(items, num):
    new = np.zeros(num,dtype=object)
    for i in items:
        if new[i[0]] == 0:
            new[i[0]] = Node(i[1],i[2])
        else:
            current = Node(i[1],i[2])
            current.next = new[i[0]]
            new[i[0]] = current
    return new

In [67]:
# task 01
def max_degre_2(items, num):
    arr = tuple_to_array(items, num)
    temp = max_edges_2(arr)
    head = temp[0] 
    print("Vertex with max degree: ",end='')
    while head:
        print (head.val,end=' ')
        head = head.next
    print()
    print("max degree ",temp[1]) 


graph = ((3, 6),(6, 7),(6, 8),(6, 9),(9, 10),(0, 3),(2, 5),(0, 4),(0, 5),(1, 4),(1, 5),(2, 3),(2, 4),(4, 5),(7, 8),(8, 9),(7, 9))
max_degre_2(graph, 11)

Vertex with max degree: 4 5 6 9 
max degree  4


In [68]:
# task 02
def max_weight_2(items, num):
    arr = tuple_to_weight_array(items, num)
    temp = max_edges_2(arr)
    head = temp[0]
    print("Vertex with max edge weight: ",end='')
    while head:
        print (head.val,end=' ')
        head = head.next
    print()
    print("max edge weight ",temp[1])

graph = ((3, 6, 10),(6, 7, 5),(6, 8, 5),(6, 9, 5),(9, 10, 40),(0, 3, 10),(2, 5, 20),(0, 4, 5),(0, 5, 15),(1, 4, 15),(1, 5, 10),(2, 3, 10),(2, 4, 15),(4, 5, 25),(7, 8, 10),(8, 9, 5),(7, 9,20))
max_weight_2(graph, 11)

Vertex with max edge weight: 5 9 
max edge weight  70


In [69]:
# task 03
# sub task 01
def max_out_degree_2(items, num):
    arr = tuple_to_direct_array(items, num)
    temp = max_edges_2(arr)
    head = temp[0]
    print("Vertex with max out degree: ",end='')
    while head:
        print (head.val,end=' ')
        head = head.next
    print()
    print("max out degree ",temp[1])
    
# sub task 02
def max_out_weight_2(items, num):
    arr = tuple_to_direct_weight_array(items,num)
    temp = max_edges_2(arr)
    head = temp[0]
    print("Vertex with max out weight: ",end='')
    while head:
        print (head.val,end=' ')
        head = head.next
    print()
    print("max out weight ",temp[1])

graph = ((3, 6),(6, 7),(6, 8),(6, 9),(9, 10),(0, 3),(2, 5),(0, 4),(0, 5),(1, 4),(1, 5),(2, 3),(2, 4),(4, 5),(7, 8),(8, 9),(7, 9))

max_out_degree_2(graph, 11)
print()         

graph = ((3, 6, 10),(6, 7, 5),(6, 8, 5),(6, 9, 5),(9, 10, 40),(0, 3, 10),(2, 5, 20),(0, 4, 5),(0, 5, 15),(1, 4, 15),(1, 5, 10),(2, 3, 10),(2, 4, 15),(4, 5, 25),(7, 8, 10),(8, 9, 5),(7, 9,20))
max_out_weight_2(graph, 11)

Vertex with max out degree: 0 2 6 
max out degree  3

Vertex with max out weight: 2 
max out weight  45


In [74]:
def direct_to_undirect_2(items, num):
    arr = tuple_to_direct_weight_array(items, num)
    new = np.zeros(num, dtype= object)

    for i in range(len(arr)):

        if arr[i] != 0:
            head = arr[i]
            while head:

                if new[i] == 0:
                    new[i] = Node(head.val, head.weight)
                else:
                    current = Node(head.val, head.weight)
                    current.next = new[i]
                    new[i] = current
                
                if new[head.val] == 0:
                    new[head.val] = Node(i, head.weight)
                else:
                    current = Node(i, head.weight)
                    current.next = new[head.val]
                    new[head.val] = current
                
                head = head.next

    return new

graph = ((3, 6, 10),(6, 7, 5),(6, 8, 5),(6, 9, 5),(9, 10, 40),(0, 3, 10),(2, 5, 20),(0, 4, 5),(0, 5, 15),(1, 4, 15),(1, 5, 10),(2, 3, 10),(2, 4, 15),(4, 5, 25),(7, 8, 10),(8, 9, 5),(7, 9,20))
new = direct_to_undirect_2(graph, 11)
for i in range(len(new)):
    print("Idx ",i,end="--->")
    head = new[i]
    if head == 0:
        pass
    else:
        while head:
            print(head.val,end="->")
            head = head.next
    print()

Idx  0--->3->4->5->
Idx  1--->4->5->
Idx  2--->5->3->4->
Idx  3--->6->2->0->
Idx  4--->5->2->1->0->
Idx  5--->4->2->1->0->
Idx  6--->7->8->9->3->
Idx  7--->8->9->6->
Idx  8--->9->7->6->
Idx  9--->10->8->7->6->
Idx  10--->9->
